version: '3.8'

services:
  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
      MB_DB_FILE: /metabase/metabase.db
    volumes:
      - ./metabase:/metabase-data
    depends_on: 
        - postgres
    networks:
      - metabase-network

  postgres:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase
    volumes:
      - ./pg/data.db:/var/lib/postgresql/data
    networks:
      - metabase-network

networks:
  metabase-network:
    driver: bridge