version: "3.7"
services:
  p3:
    image: eclipse-mosquitto:latest
    container_name: p3
    ports:
      - "1891:1883" 
      - "9001:9001" 
    volumes:
      - ./config:/mosquitto/config:ro
      - ./data:/mosquitto/data:ro
      - ./log:/mosquitto/log:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 100M

volumes:
  config:
  data:
  log:

networks:
  default:
    name: p3-network
