name: Ponderada 4 - Automatização de Testes Unitários e de Integração

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ponderada_4/**'

jobs:
  Integration-Tests:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: ['3.10']

    defaults:
      run:
        shell: bash
        working-directory: './ponderada_4/mqtt'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Temp .env file
        run: |
          touch .env
          echo BROKER=${{ secrets.P4.BROKER }} >> .env
          echo PORT=${{ secrets.P4.PORT }} >> .env
          echo TOPIC=${{ secrets.P4.TOPIC }} >> .env
          echo QOS=${{ secrets.P4.QOS }} >> .env
          echo USER=${{ secrets.P4.PROFILE }} >> .env
          echo PASSWORD=${{ secrets.P4.PASSWORD }} >> .env
          echo CLIENT_ID=${{ secrets.P4.CLIENT_ID }} >> .env
          cat .env
      - name: Tox run 
        run: tox run-parallel