name: Ponderada 2 - Automatização de Testes

on:
  push:
    branches:
      - 'main'
    

jobs:
  create-broker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: '../'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: '1.6'
          ports: '1891:1891'
          config: ../mosquitto.conf
          container-name: 'mqtt'

  test:
    needs: create-broker
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: ['3.10']

    defaults:
      run:
        shell: bash
        working-directory: './ponderada_2/mypkg'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Unity and Integration Tests
        run: tox